### PR TITLE
Docs: colorbutton review.

### PR DESCRIPTION
**Pull request by godai78**
To major, as it was merged w/ major.

### CODE REVIEW

**Review by f1ames — COMMENTED** [review]
Just a side-note from me, `repos/ckeditor-presets` submodule shouldn't be updated IMHO. I assume it's caused by the fact that working branch originates from `stable`/`master,` but still shouldn't be commited.

**Comment by godai78** [comment]
@f1ames - wasn't intentional at all, most probably what You say.

**Comment by godai78** [comment]
PR: #319

**Comment by godai78** [comment]
Closing conflicting PR, #320 takes over the merge.

**Pull request closed without merging**
