### PR TITLE
Add guide about integrating with webpack

### PR DESCRIPTION
**Pull request by Comandeer**
I've added guide with minimal, basic integration with webpack.

I've also created sample repository with such integration: https://github.com/ckeditor/ckeditor4-webpack-template

Closes ckeditor/ckeditor4#3045.

### CODE REVIEW

**Comment by f1ames** [comment]
Rebased onto latest `stable`.

**Comment by Comandeer** [comment]
Added sample HTML.

**Comment by f1ames** [comment]
Rebased onto latest `stable`.

**Comment by f1ames** [comment]
Rebased onto latest `stable`.

**Pull request merged**
