### PR TITLE
Colorbutton 2

### PR DESCRIPTION
**Pull request by godai78**
Additional review and fixes for the color button docs.  
  
From: cksource/content-documentation-proofread#312

### CODE REVIEW

**Comment by f1ames** [comment]
This PR should target `major` too I suppose instead of stable.

**Comment by godai78** [comment]
@f1ames - yes, the power of habit, sorry. Corrected.

**Review by AnnaTomanek — APPROVED** [review]
All screenshots redone, content corrected, sample fixed.

**Comment by AnnaTomanek** [comment]
The GIF (screencast) would look better if it weren't cut from the top and right-hand side.

**Review by f1ames — APPROVED** [review]
LGTM :+1:

**Comment by f1ames** [comment]
Rebased onto latest `major`.

**Pull request merged**
