### PR TITLE
Add docs for color history feature

### PR DESCRIPTION
**Pull request by Dumluregn**
Introduced in https://github.com/ckeditor/ckeditor4/pull/3784, color history feature lacks the proper documentation besides API docs. This PR add some information about using it as well as the examples.

Closes https://github.com/ckeditor/ckeditor4/issues/4237.

Sorry the gif quality - that's the best what my recording software achieved. For sure it needs to be done better.

### CODE REVIEW

**Comment by f1ames** [comment]
Overtook this PR since @Dumluregn is off.

**Comment by f1ames** [comment]
@godai78 could you review it?

Also it would make sense to redo outdated screenshots in features section. I lack HiDPI device ATM so it would be good if someone with such device can do this. @godai78 can I ask you to cover this also? If not, we will find another volunteer ;)

**Comment by godai78** [comment]
I will look to it soon as I can.

**Comment by f1ames** [comment]
> It looks in fact to be doable (1, 2), so I will check how it looks.

Doable, after forcing `CKEDIOTR.env.hidpi = true` in CKEditor so HiDPI icons are used too. Anyway, after I've done screenshots and cut them nicely, I realized that editor language was set to `pl` (due to browser settings) so I have to redo them in English once again :sob: :facepalm:

**Pull request merged**
