### PR TITLE
Document use of CKEDITOR.dtd object

### PR DESCRIPTION
**Pull request by lkmorlan**
This allows defining an element as block level or empty.

### CODE REVIEW

**Comment by Dumluregn** [comment]
Hello, I need to rebase your PR - could you allow for changes in this PR?

**Comment by lkmorlan** [comment]
What do I have to do to allow that?

**Comment by f1ames** [comment]
Hi @lkmorlan, please see https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork :+1:

**Comment by lkmorlan** [comment]
"Allow edits by maintainers" is already checked. In any case, I have rebased it.

**Comment by jacekbogdanski** [comment]
@Dumluregn I also have a feeling that this information doesn't really fit here. I may be wrong, but it's probably not a very popular use case to add additional elements via plugins to the editor? In that case, maybe it better fits just API docs of https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dtd.html ?

**Comment by Dumluregn** [comment]
> maybe it better fits just API docs

Yeah, that makes sense :+1: So I'm closing this PR and opening one in the `ckeditor4` repo.

**Pull request closed without merging**
