### PR TITLE
Added required config option for cke >= 4.9

### PR DESCRIPTION
**Pull request by f1ames**
See https://github.com/ckeditor/ckeditor4-docs/pull/217#issue-246363498:

> References:
>
> https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html
>
> ckeditor/ckeditor4#1894
>
> ckeditor/ckeditor4#2768

Closes [ckeditor/ckeditor4#3773](https://github.com/ckeditor/ckeditor4/issues/3773).

### CODE REVIEW

**Comment by Dumluregn** [comment]
According to the Slack conversation I've change target branch from `master` to `stable`.

**Comment by Dumluregn** [comment]
I added some extra comment here based on #279, I think it's ready to review now.

**Comment by f1ames** [comment]
Rebased onto latest `stable`.

**Comment by f1ames** [comment]
Looks good, @AnnaTomanek can you take a final look on this one?

**Comment by f1ames** [comment]
Thank you again for contribution @klemens-u and @MADronov!

**Pull request merged**
