### PR TITLE
Docs: 4.16 review.

### PR DESCRIPTION
**Pull request by godai78**
Minor fixes for the 4.16 docs changes.

### CODE REVIEW

**Review by f1ames — APPROVED** [review]
:+1:

**Review by AnnaTomanek — APPROVED** [review]
All done. It was funny to review and correct something that probably went back to Fred or Garry (the Skin SDK guide).

**Comment by AnnaTomanek** [comment]
It looks, though, that the previous commit included some `ckeditor-presets` files so you might want to remove it before merging, @f1ames.

**Comment by f1ames** [comment]
Rebased onto latest `major`.

**Pull request merged**
