### PR TITLE
Rework the "Paste from *" samples

### PR DESCRIPTION
**Pull request by Dumluregn**
I've added a second editor instance with full preset and disabled ACF to show the full power of plugins. Also included a small fix for the downloadable snippets (they were missing the line with editor element).

Closes https://github.com/ckeditor/ckeditor4/issues/4517.

### CODE REVIEW

**Review by f1ames — CHANGES_REQUESTED** [review]
Generally looks good - two editor instances makes sense to show both the power of Paste from Word and the way how it can be customized.

---

The separation of both sample is hardly visible so I would be for placing them in the separate sections to underline what are the differences here. For example:

1.  Intro section
2.  Pasting content without filtering (first sample)
3.  Filtering pasted content with ACF (second sample)

Then we will also have nice ToC on the right-side. Each sample section could have short description (as you already added before each editor instance). @Dumluregn could you tak care of that?

---

The 2nd sample (and the only one we have for now) has a slightly adjusted CSS styling to reflect Word content a little better. This is visible for paragraph margins which might be bigger than in Word document. Still I guess we don't want to fiddle with this, since there is no perfect styling and it's just CSS configurable as mentioned in the sample description itself.

---

I have also reported one feature request related to supporting cropped image while checking this PR - ckeditor/ckeditor4#4574.

---

And this makes me really uncomfortable, it works fine for other samples and I know that it was done on purpose to have better "document/page" like feeling but still...



And I would say it's broken because for smaller browser sizes there is no horizontal scrollbar so part of the editor is simply hidden:



@Dumluregn could you also take care of that (or at least see how it would look)?

**Comment by Dumluregn** [comment]
> The separation of both sample is hardly visible so I would be for placing them in the separate sections to underline what are the differences here. For example:

> Intro section
> Pasting content without filtering (first sample)
> Filtering pasted content with ACF (second sample)

> Then we will also have nice ToC on the right-side. Each sample section could have short description (as you already added before each editor instance).

I've added headers, but as mentioned in https://github.com/ckeditor/ckeditor4/issues/4581, ToC is not created for examples. 

---

> I also wonder, maybe we can have different samples content? The one with ACF off could use our "complex" document sample. However, then "Recognition of Achievement" should be the first sample as it's more representative I suppose.

I went with the following pattern:

```
editor 1 content:
- recognition of achievement

editor 1 file:
- mixed styles


editor 2 content:
- bilancino hotel (from https://ckeditor.com/ckeditor-4/demo/#document)

editor 2 file:
- recognition of achievement
```

This way we have:
1) different content in both editors,
2) content in each sample is different than in corresponding file.

However TBH I'm still not super satisfied as all the sample content looks almost the same in both editors. Maybe we should invest some more time and create samples with content which would actually be filtered in the second editor (or change configuration)? Now besides some descriptions it is hard to notice that it filters anything. The lack of simple things like colors and links would be easily noticeable and makes some sense.

---

> The 2nd sample (and the only one we had for now) has a slightly adjusted CSS styling to reflect Word content a little better. This is visible for paragraph margins which might be bigger than in Word document. Still I guess we don't want to fiddle with this, since there is no perfect styling and it's just CSS configurable as mentioned in the sample description itself. So I would leave it as is. WDYT?

I wouldn't touch it neither.

---

> And this makes me really uncomfortable, it works fine for other samples and I know that it was done on purpose to have better "document/page" like feeling but still...

Glad you mentioned it. I've reduced the editor width and the content padding. I think it still looks acceptable. Note that the width is explicitly set to the value it would have anyway, but then the editor changes the size together with a page so I've decided to keep it constant.

**Review by f1ames — CHANGES_REQUESTED** [review]
Looking better and better :+1:

> I've added headers, but as mentioned in [ckeditor/ckeditor4#4581](https://github.com/ckeditor/ckeditor4/issues/4581), ToC is not created for examples.

:+1:

> This way we have:
> 
> 1.  different content in both editors,
> 2.  content in each sample is different than in corresponding file.

The idea with different samples than editor content can show editor capabilities better, but OTOH one would not be able to see how it works with initial content which was also important here - to show that the content editor was initialized with can be exactly the same as one pasted from Word.

> However TBH I'm still not super satisfied as all the sample content looks almost the same in both editors. Maybe we should invest some more time and create samples with content which would actually be filtered in the second editor (or change configuration)? Now besides some descriptions it is hard to notice that it filters anything. The lack of simple things like colors and links would be easily noticeable and makes some sense.

This makes me think that it could be a good idea to have one docx sample with some more extensive styling (e.g. we could adjust "recognition of achievement" one) and have first editor without ACF which accepts all the styling. And then second editor with some filtering added and explained, for example: "The editor below have ACF enabled which filters tables, background colors and italics..." and then it will be clearly visible what can be disabled and how it works. One can paste same content to both instances and see the difference. WDYT?

Ofc, we can have link to fancy docx somewhere there as we have now but only as an extra.

And regarding Excel sample, we probably would be not able to come up with anything fancy here, maybe the second editor could simply strip colors (and maybe alignment) to show styling can be filtered out?

---

> Glad you mentioned it. I've reduced the editor width and the content padding. I think it still looks acceptable. Note that the width is explicitly set to the value it would have anyway, but then the editor changes the size together with a page so I've decided to keep it constant.

Looks better, however there are some inconsistencies with line breaks. Before (and the same as in the Word document) it was:



and now it is:



it seems it's enough to change page width to `15.6cm` to get back to consistent line breaks:



---

I think it will be good to try to minimize buttons on first editor instance too, since it looks like "too much" now. Maybe we could have both editors have consistent toolbars simply?

**Comment by Dumluregn** [comment]
Please note that I've only applied changes to `Paste from Word` and `Paste from Excel` to save some time - after we approve them, I'll alter the rest of samples.

> The idea with different samples than editor content can show editor capabilities better, but OTOH one would not be able to see how it works with initial content which was also important here - to show that the content editor was initialized with can be exactly the same as one pasted from Word.

Ok, I've restored the same content in the samples.

> This makes me think that it could be a good idea to have one docx sample with some more extensive styling (e.g. we could adjust "recognition of achievement" one) and have first editor without ACF which accepts all the styling. And then second editor with some filtering added and explained, for example: "The editor below have ACF enabled which filters tables, background colors and italics..." and then it will be clearly visible what can be disabled and how it works. One can paste same content to both instances and see the difference. WDYT?

Done with the comments what is removed from the samples (images and tables for Word, colors and alignment for Excel).

> EDIT: Now I see it is fine, maybe some cache issue 🤔 @Dumluregn could you confirm it works for you? 🤔

Yup, it aligns rows the same as on current stable for me.

> I think it will be good to try to minimize buttons on first editor instance too, since it looks like "too much" now. Maybe we could have both editors have consistent toolbars simply?

I've chopped some unimportant plugins (like `forms` or `iframe` and improved grouping to fit all the buttons in 3 rows, looks pretty good for me now. As for the consistent toolbars between the samples - isn't it impossible? I mean if we use ACF to remove some content from the second editor, then toolbar buttons disappear automatically, so we'd have to also disable the feature in the first editor, which is probably what we wanted to avoid in the first place 😛

**Review by f1ames — CHANGES_REQUESTED** [review]
Ok, looking good :+1:

I have only covered some minor rewording (see 54c51b7) and added empty paragraph after table to initial content (29db371) - it wasn't there before but I see it's added when pasting from Word (@Dumluregn can you confirm it happens to you too?).

> I've chopped some unimportant plugins (like `forms` or `iframe` and improved grouping to fit all the buttons in 3 rows, looks pretty good for me now. As for the consistent toolbars between the samples - isn't it impossible? I mean if we use ACF to remove some content from the second editor, then toolbar buttons disappear automatically, so we'd have to also disable the feature in the first editor, which is probably what we wanted to avoid in the first place

TBH, I had a hard time recalling:older\_man: if removing buttons via [`toolbarGroups`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-toolbarGroups) config affects also plugins (by removing them) but yeah that's the case here so as you mentioned it's not really doable.

---

I'm giving R- so after other samples are adjusted I will take a final look and then we can ask @godai78 for a grammar review.

**Review by f1ames — APPROVED** [review]
Added minor corrections here and there and we are good to go :tada: Good job @Dumluregn :+1: 

@godai78 could you take a final look on this one?

**Comment by godai78** [comment]
Sure.

**Comment by godai78** [comment]
The **Source** toolbar button position is different in the "old" and the "new" demo samples. It should be the same in both, to avoid confusion. @Dumluregn, can you look to it?

**Review by godai78 — APPROVED** [review]
Introduced some minor fixes, see no other fallacies except the toolbar arrangement, hence I accept this PR.

**Comment by f1ames** [comment]
> The **Source** toolbar button position is different in the "old" and the "new" demo samples. It should be the same in both, to avoid confusion. @Dumluregn, can you look to it?

Those two editor instances have different set of features enabled and different set of buttons in the toolbar. So moving `Source` to the end in the first instance still would look different than the 2nd instance. Also there is no physical space there so it will result in additional toolbar line being added (or we can try to reorganize entire toolbar then).

I would say this is our standard/default toolbar so it's acceptable. The 2nd example has toolbar fitted better to paste sample (paste button as a first element) so the change in `Source` button position seems acceptable there two I suppose :thinking: 

@Dumluregn WDYT? Do you have any ideas how it could be reordered so both editors have more consistent toolbars?

**Comment by Dumluregn** [comment]
It's worth to remember that the first sample is about to show the `full` preset capabilities, so I think it makes sense to keep the toolbar as similar to the one in mentioned preset as possible. Sadly, it's not exactly possible since the editor in docs samples is not as narror as e.g. on [CDN](http://cdn.ckeditor.com/4.16.0/full-all/samples/index.html), so we have to adjust the layout (by e.g. kicking some stuff out) or we end up with 5 rows 😱  So my proposal is to keep the `Source` button at the beginning to not alter the default full preset toolbar more and modify the second one accordingly:

First editor:
Screenshot 2021-04-15 at 14 59 42

Second editor:
Screenshot 2021-04-15 at 15 06 11


If you both accept it, I'll push a patch changing it in all samples.

**Comment by godai78** [comment]
I like this ^. It does exactly what I had in mind mentioning this issue. Thank you.

**Review by f1ames — APPROVED** [review]
:+1: :tada:

**Pull request merged**
