### PR TITLE
Added required config option for cke >= 4.9

### PR DESCRIPTION
**Pull request by klemens-u**
References: 

https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html

https://github.com/ckeditor/ckeditor-dev/issues/1894

https://github.com/ckeditor/ckeditor-dev/issues/2768

### CODE REVIEW

**Comment by fsoedjede** [comment]
Thanks, this just saved me

**Comment by klemens-u** [comment]
Pls pull, tnx!

**Comment by f1ames** [comment]
Thank you for contributing @klemens-u! We will take a look on this PR soon.

**Comment by f1ames** [comment]
Hello @klemens-u, we had some issue during rebase/push to your PR branch (not sure what exactly happened :thinking:). Anyway, we copied the branch to our remote and will be processing your PR in #285.

**Pull request closed without merging**
